# -*- coding: utf-8 -*-
"""Copy of python_basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14SpVJbCsz0NXkLct1lSDI0jDoLGKQ5B2
"""

# print("Hello World")
a=3
# print(a)
type(a)
string="Kushagra"#->string
type(string)
flag= False #--> boolean
type(flag)
# True/False ->It will throw error
c=5-6j
type(c)
c.imag
c.real

#Rules to define the variable
# 1.Should start with the alphabaet and "_"(underscore)
# 1name=2 ->Invalid
_name="Kushagra"

# 2. should make sense
# Name that make sense for the variable value
abc="Delhi"
city="Delhi" #it is good practice

# 3.LHS should have no space
# data anlytics="Hello"

"""
Multiline comment
here
"""
#List of all the keywords in python
# help("keywords")

# Indentation
#statement
# expression

#Standard input and output in python->always string
# name= input("Enter your name :")
# print(name)

age=input("Enter your age")
age=int(age);

type(age)



"""# Mutability"""

#Mutability and immutability in python
name="Kushagra"
print(name[0])# 0 based left to right indexing
print(name[-8])# -1 based indexing right to left

#Other type of data container
#List can store any type of value int boolan same as the javascript ->Bag that can store anytpe of value
list_container=[1,2,3,"Ajay",True]
print(list_container)


#Change the element in the container->Mutable
list_container[3]="Kushagra"
print(list_container)

#Other type of sequence container can store only one type of container

# Immutable means it can not be within the same ways indexing as the in list dictonanry in Python
#String tuples are immutable in Python
#  course="DataScience"
#  course[2]='c'

"""# Operators

"""

#operator->special keywords in python in order to do the operation

a=11;
b=10;

#Arithmatic Operators
# print(a+b)
# print(a-b)
# print(a/b)
# print(a*b)
# print(a**b)#power operator
# print(a%b)
# print(a//b) #floor division-> give you lowest nearest integer

#Comparision Operator
# print(a==b)
# print(a<=b)
# print(a>=b)
# print(a<b)
# print(a>b)
# print(a!=b)


#Assignment operator
# a=12
# a+=10
# b-=10
# b*=10
# b/=10
# b**=2
# print(b)



#Logical operator->True/False
res=(a>b)and(b<=9)
# print(res)

#Membership operator-> Used in sequence data
course="PwSkillsAi"

#in operator
"P" in course# true

#not in operator
"P" not in course #false


#Identity Operator -> Are both mapping to same memory location
Kushagra ="Student"
abhay=Kushagra

# Kushagra is abhay
# Kushagra is not abhay


# oct(1)
# bin(18)-> Ninary representation of 18

#Bitwise Operator->Operation at bitlevel
18&3
18|2
16>>3#right shift(Divide by 2^3)
2<<3#Left shift(Multiply by 2^3)

"""# Type Casting

"""

from ast import Str
#implicit coversion don already by python itself

#Explicit Conversion ->Done manulllay python can't do it

# 1.int
# 2.Str
# 3.bool
# 4.float

# y = "1"
# c= int(y)
# type(c)
# d= float(y)
# type(d)
# e=bool(y)
# type(e)

"""# Conditionals in Python


"""

#if else conditionals

# if 2>3:
#   print("2 > 3")
# else:
#   print("2<3")
#   print(2+3)
#   print(2-3)

# if(7%2==0):
#   print("even")

# else: print("Odd")

num=31
# if(num<30):
#   print("Failed")
# elif( num>30 and num<60):
#     print("grade B")
# else :
#   print("Grade A")

# hour=14
# if(hour<12) :
#   print("Good Morning!")
# elif(12<=hour<=17):
#   print("Good Afternoon")
# else:
#   print("Good Evening")

x=6
y=4
#Nested if else
# if(x>5):
#   if(y<5):
#     print("x> 5 and y < 5")

# a= int(input("Enter a number"))
# if(a>100):
#   print("Number is greater than 100")
# else :
#   print("Number is less than 100")

name= input("Enter you name :")
email= input("Enter your email :")
password= input("Enter your password :")

if(name==""):
    print("Enter valid name")
elif(password=="" or email=="" or "@" not in email or len(password)<8):
    print("Password and email must be valid")
else:
    print("Registeration Successfull")

"""# Loops

"""

# n =7
# i=0

#While Loop in Python
# while(i<7):
#   i+=1;
#   if(i==3):continue
#   print(i)
#   if(i==6) : break


#For Loop
# a= "Kushagra Awasthi"
# for char in a:
#   if(char=="a") :continue
#   print(char)


#Range
# range(0,10)
# list(range(0,10))
# list(range(2,10,2))# 2 se start kro aur  har 2nd element lo
# for i in range(0,10):
#   print(i)

# row=1;
# while (row<=4):
#   col=1
#   while(col<=row):
#     print("*", end="$")# end mtlb har * ke baad ye $ ayega
#     col+=1
#   print()#New Line
#   row=row+1

# course=["AI","Data Science","COA","DSA","Development"]
# for i in range(len(course)):
#   print(course[i])

# for i in range(4):
#   for j in range(i+1):
#     print('*',end="")
#   print()

number=[1,2,3,4,5,6,7]
for num in number:
  if(num==3)or(num==7):
    break
  print(num)